{% set version = "0.13.1" %}

package:
  name: reproject
  version: {{ version }}

source:
  fn: reproject-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/reproject/reproject-{{ version }}.tar.gz
  md5: 19076686f302fc52aba977dd5c7e83a3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38 or python_impl == 'pypy']


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython =3.0.4                          # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - pip
    - setuptools
    - setuptools-scm
    - wheel
    - cython =3.0.4
    - extension-helpers
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - astropy >=5.0
    - astropy-healpix >=0.6
    - scipy >=1.5
    - dask >=2021.8
    - cloudpickle
    - zarr
    - fsspec
    - shapely

test:
  requires:
    - pytest-astropy
  imports:
    - reproject
    - reproject.healpix
    - reproject.interpolation
    - reproject.spherical_intersect
  commands:
    - python -c "import reproject"

about:
  home: http://reproject.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The reproject package implements image reprojection (resampling) methods for astronomical data.

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
    - bsipocz
    - Cadair
