{% set version = "0.14.1" %}

package:
  name: reproject
  version: {{ version }}

source:
  fn: reproject-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/r/reproject/reproject-{{ version }}.tar.gz
  md5: a09c29e849824d5867d614bfdc530730

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310 or python_impl == 'pypy']


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.4,<3.1.0                  # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - pip
    - setuptools
    - setuptools-scm
    - wheel
    - cython >=3.0.4,<3.1.0
    - extension-helpers
  run:
    - python
    - numpy >=1.23
    - astropy-base >=5.0
    - astropy-healpix >=1.0
    - scipy >=1.9
    - dask >=2021.8
    - cloudpickle
    - zarr
    - fsspec
    - shapely

test:
  requires:
    - pytest-astropy
  imports:
    - reproject
    - reproject.healpix
    - reproject.interpolation
    - reproject.spherical_intersect
  commands:
    - python -c "import reproject"

about:
  home: http://reproject.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The reproject package implements image reprojection (resampling) methods for astronomical data.

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
    - bsipocz
    - Cadair
