{% set version = "0.4" %}

package:
  name: reproject
  version: {{version}}

source:
  fn: reproject-{{version}}.tar.gz
  url: https://pypi.io/packages/source/r/reproject/reproject-{{ version }}.tar.gz
  md5: 56777bf5c2f8e2a7c0a05b3d058943c2

build:
  number: 1
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - setuptools
    - cython

  run:
    - python
    - numpy
    - astropy >=2.0
    - scipy >=0.9
    - astropy-healpix >=0.2

test:
  imports:
    - reproject
  commands:
    - python -c "import reproject; reproject.test()"

about:
  home: http://reproject.readthedocs.io
  license:  BSD 3-Clause
  summary: "The reproject package implements image reprojection (resampling) methods for astronomical data."

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - mwcraig
