appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CW0+FfpycBj/c0gIvXFSCftKhCS3J0walWBzHLpaDaM0h2X51eXLnIhh8f4xvHVAHvLCBE3n4SfpNBYF6ItGJduJXLojGh3eekMqkDNaKuu15B+UHXuQIYREEF3j9hhbPTCNmEVEdz5eyW9sA/IOCUPeOIf2UPxz0052+3Vmrso0fp5T8Z+jt+zKuC5Y7GZK8wJjXua0kaHgJ1IXvN3nIqYTOWj3f8LF6mb2X+c1h9h1tmC0xOoMils2/e2rYByomzrTmJlxS/HJr3Cr+HVeAMntcPOEX2RBmOnJpeIk6SCoWitdIjpwmyctTHOC96KL6OffhtogJWYChuRhPVk18M5xcEqB5F/iCslzejIlaw501MXSttIa7Yug+bOcXJgH81f5N1vmoTMJTBEcIJhtYZTm7Jo6iJt1a2btLushtE9Y7gyTz0cSy9w8Xxq/0RW63wMUV/UxddFnAhPzBnlS7qj+lsGZQu0lXR8kv5xh385qAm0V8K12IaSGjhC7L7k+32HyewZLSPGtOBjdeB+ZuCXs/mstV/9CPB1Zm08I4lHSe67YJM/4auiJKucgxqS4T3kYozAVaz9LZYdG69AaXrOJEyYditMz6BDnGISCnAV8WCZ+zTStO3vJHwR/RXq2DgvJIdSYpyYOUzh4yQybbjsfARbqRnk4KCoEV0+zwGU=}
